// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJkV16COi0TBnXBsyumAGDO-F14uKeQv0',
    appId: '1:736912816865:web:47a3084a597d7bbc6d55a0',
    messagingSenderId: '736912816865',
    projectId: 'capstone-d4456',
    authDomain: 'capstone-d4456.firebaseapp.com',
    storageBucket: 'capstone-d4456.firebasestorage.app',
    measurementId: 'G-2FPP7VH2E4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBAXi6NorEdLyaCRbQy7ZVWguLpexoZ3s',
    appId: '1:736912816865:android:e17d674616f98c066d55a0',
    messagingSenderId: '736912816865',
    projectId: 'capstone-d4456',
    storageBucket: 'capstone-d4456.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDop2b-Lk9kZBHM9T9xIT5iyUF567dhjHc',
    appId: '1:736912816865:ios:b6cd9d3a676596f26d55a0',
    messagingSenderId: '736912816865',
    projectId: 'capstone-d4456',
    storageBucket: 'capstone-d4456.firebasestorage.app',
    iosBundleId: 'com.example.capstone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDop2b-Lk9kZBHM9T9xIT5iyUF567dhjHc',
    appId: '1:736912816865:ios:b6cd9d3a676596f26d55a0',
    messagingSenderId: '736912816865',
    projectId: 'capstone-d4456',
    storageBucket: 'capstone-d4456.firebasestorage.app',
    iosBundleId: 'com.example.capstone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJkV16COi0TBnXBsyumAGDO-F14uKeQv0',
    appId: '1:736912816865:web:fbd80342a253e5de6d55a0',
    messagingSenderId: '736912816865',
    projectId: 'capstone-d4456',
    authDomain: 'capstone-d4456.firebaseapp.com',
    storageBucket: 'capstone-d4456.firebasestorage.app',
    measurementId: 'G-DF0JN1N3EH',
  );
}
